version: '3.7'

services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: webapp
      POSTGRES_USER: devbox
      POSTGRES_PASSWORD: devbox
    ports:
      - 5432:5432
    